# Generated by Django 3.2.9 on 2021-11-15 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Done',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('interval', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('done', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='habits_tracker_groupe.done')),
            ],
        ),
    ]
