# Generated by Django 3.2.9 on 2021-11-15 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits_tracker_groupe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='done',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='HabitDone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits_tracker_groupe.done')),
                ('habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits_tracker_groupe.habit')),
            ],
        ),
    ]
