# Generated by Django 3.2.9 on 2021-11-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits_tracker_groupe', '0002_auto_20211115_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='done',
            name='habits',
            field=models.ManyToManyField(related_name='habits_dones', to='habits_tracker_groupe.Habit'),
        ),
        migrations.DeleteModel(
            name='HabitDone',
        ),
    ]
