# Generated by Django 3.2.9 on 2021-11-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits_tracker_groupe', '0003_auto_20211115_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='done',
        ),
        migrations.AlterField(
            model_name='done',
            name='habits',
            field=models.ManyToManyField(blank=True, null=True, related_name='habits_dones', to='habits_tracker_groupe.Habit'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='interval',
            field=models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly')], max_length=1),
        ),
    ]
